# fly.toml app configuration file generated for gholink on 2025-11-25T21:44:58Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gholink'
primary_region = 'lax'

[build]

# Serve the Vite dist folder
[[statics]]
  guest_path = "/app/dist"
  url_prefix = "/"

# Remove ALL http_service and internal_port settings
# (your app does not run a server)
